CREATE DATABASE IF NOT EXISTS test;
USE test;
DROP TABLE IF EXISTS staff;
CREATE TABLE staff
(
  id   INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NULL
);

INSERT INTO staff (name) VALUES (1,'Alice');
INSERT INTO staff (name) VALUES ('Bob');
INSERT INTO staff (name) VALUES ('test');
