name: C++ CI

on:
  push:
    paths:
      - '.github/workflows/cpp.yml'
      - 'c_cplusplus/**'
  pull_request:
    paths:
      - '.github/workflows/cpp.yml'
      - 'c_cplusplus/**'

jobs:
  ci:
    strategy:
      matrix:
        module:
          - name: 'mysql-connector-cpp'
            with_oceanbase_container: true
    uses: ./.github/workflows/basic-workflow.yml
    with:
      language: 'cpp'
      module: ${{ matrix.module.name }}
      with_oceanbase_container: ${{ matrix.module.with_oceanbase_container }}